version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/camera-ui-*"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "typescript"
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/camera-ui-*"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directories:
      - "/camera-ui-*"
    schedule:
      interval: daily
