audio-yamnet:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-audio-yamnet/**'
coral:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-coral/**'
coreml:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-coreml/**'
eufy:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-eufy/**'
hailo:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-hailo/**'
homekit:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-homekit/**'
ncnn:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-ncnn/**'
onnx:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-onnx/**'
onvif:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-onvif/**'
opencl:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-opencl/**'
opencv:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-opencv/**'
openvino:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-openvino/**'
pamdiff:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-pamdiff/**'
reolink:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-reolink/**'
ring:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-ring/**'
rust-motion:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-rust-motion/**'
smtp:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-smtp/**'
tuya:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-tuya/**'
wasm-motion:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-wasm-motion/**'
wyze:
  - changed-files:
      - any-glob-to-any-file: 'camera-ui-wyze/**'

# Cross-cutting labels.
externals:
  - changed-files:
      - any-glob-to-any-file: 'externals/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file: '**/package.json'
      - any-glob-to-any-file: '**/package-lock.json'
      - any-glob-to-any-file: '**/requirements.txt'

workflow:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

docs:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
