DEFAULT_AREA = 350
DEFAULT_AREA_FD = 350
DEFAULT_AREA_BS = 350

DEFAULT_THRESHOLD = 50
DEFAULT_VAR_THRESHOLD_BS = 18

DEFAULT_BLUR = 11
DEFAULT_DILT = 5
DEFAULT_LEARNING_RATE = 0.9

AVAILABLE_MODELS = ["Frame Difference", "Background Substraction", "Default"]


DEFAULT_MODEL = "Background Substraction"
